on:
  # Workflows check plugin Jeedom
  push:
    branches:
      - alpha
      - beta
  pull_request:
    branches:
      - alpha
      - beta
      - V4-stable

name : 'Test Core Jeedom'

jobs:
  codeLintGlobal:
    uses: jeedom/workflows/.github/workflows/codeLintGlobal.yml@main
  php73:
    uses: jeedom/workflows/.github/workflows/lint_Php73.yml@main
  php74:
    uses: jeedom/workflows/.github/workflows/lint_Php74.yml@main
  php82:
    uses: jeedom.workflows/.github/workflows/lint_Php82.yml@main
